### ISSUE TITLE
Plans for secrets

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#100]
In `docs/conceptual-docs/appmodel-overview` it was mentioned that secrets are still to be added.

Can you elaborate on the plans for this please? How do you see this?

Things that come to my mind:
- Integration with Azure Key Vault?

**Comment by tomkerkhove** [comment]
This has been released and is available here: https://docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-secrets-overview & https://docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-howto-manage-secrets

However, I don't see integration with Azure Key Vault yet - I presume this is coming?

**Comment by aljo-microsoft** [comment]
@tomkerkhove 
@drago-draganov 

Its in the plan, but no additional public details on when.
