### ISSUE TITLE
Azure DevOps Pipeline Support

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#112]
This is pretty early but are you working with the VSTS team to provide out-of-the-box support for deployments from within VSTS Release Management?

**Comment by tomkerkhove** [comment]
Is there an update on this?

**Comment by MikkelHegn** [comment]
@pulkitaggarwl to help comment

**Comment by tomkerkhove** [comment]
Bumping - What's the status here?

**Comment by anantshankar17** [comment]
We should have a document out soon to outline this.
