### ISSUE TITLE
Image tag "latest" is not supported

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#113]
Image tag "latest" is not supported, is there a particular reason for this?
![image](https://user-images.githubusercontent.com/4345663/40742654-793eb6d0-644f-11e8-8dfb-0d5a959c07ae.png)

Shouldn't the platform be flexible enough and allow me to do this? Not saying that I'm always using this but sometimes I cannot control the tagging by a 3rd party when using sidecars for example.

**Comment by mattrowmsft** [comment]
FYI latest is now supported
