### ISSUE TITLE
No detailed error information during deployment failure

### ISSUE THREAD

**Issue by jmeijrink** [Azure/service-fabric-mesh-preview#137]
Hi,

I'm trying to deploy a service fabric mesh app and receive an error I cannot pin-point to a cause. The error message is as follows: The resource operation completed with terminal provisioning state 'Failed'. 
There are no error details available.

Deployment failed. Correlation ID: d69b8993-d46f-4b28-8c9a-5457cce60256. 
{
"status": "Failed",
"error": {
"code": "ResourceDeploymentFailure",
"message": "The resource operation completed with terminal provisioning state 'Failed'."
}
}

In the activity log there is a more extended json available, but not with a more concrete error.

Who can help me with getting the root cause clear? The app is visible in the portal, I left it in failed state for now so it can still be analyzed.

**Comment by mattrowmsft** [comment]
We added a statusDetails field to the application properties which will now carry better diagnostic information.  This will get surfaced by CLI automatically.

**Comment by jmeijrink** [comment]
I can confirm that I got clear error messages now. Error was about too much public port mappings, after fixing that it deployed successful.
