### ISSUE TITLE
Provide sample with reliable collections

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#149]
Are there plans to provide a sample application/walkthrough that is using the reliable collections?

If this is already there, can you provide a link please? Couldn't find any docs on it.

**Comment by tomkerkhove** [comment]
Closing as sample is available here: https://docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-howto-deploy-app-sfreliable-disk-volume

**Comment by krlm** [comment]
@tomkerkhove Above sample shows usage of Service Fabric Reliable *volume* not Reliable *Collections*.
