### ISSUE TITLE
dotnet support

### ISSUE THREAD

**Issue by allanFunrock** [Azure/service-fabric-mesh-preview#152]
I was quite happy when I saw that the new sfaproj were using the new project system, but also  disappointed that it only works with msbuild and not dotnet. it seems the sdk is installed in `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\Sdks` rather than `C:\Program Files\dotnet\sdk\2.1.301\Sdks` 

Simply copying the sdk folder over to the dotnet location makes it work as expected

is there a reason for this or just an oversight?

**Comment by gdodd1977** [comment]
Has this actually been solved? I am currently getting this error when I do a nuget restore build step.

**Comment by sgreenmsft** [comment]
The Visual Studio tools for SF Mesh have not transitioned to using a versioned SDK.  There are some Visual Studio platform issues that are preventing us from adopting that approach at this time.
