### ISSUE TITLE
Request for Guidance - Applications with dependency on other application/container

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#158]
How can one deploy applications to Azure Service Fabric Mesh that depend on jobs to succeed or other applications that have been successfully deployed/succeeded?

## Scenario
Currently working on a scenario where I want to use [Kong](https://konghq.com/about-kong/) as an API Gateway.

![image](https://user-images.githubusercontent.com/4345663/41866820-966c0d9a-78b1-11e8-9746-3901910f41bc.png)

Kong is using an external data store, *either Cassandra or PostgreSQL*, and before you start the gateway itself there is a need to seed the data store that is backing it. More information in the [docs](https://docs.konghq.com/0.13.x/getting-started/quickstart/#start-kong).

![image](https://user-images.githubusercontent.com/4345663/41866879-c0a72a54-78b1-11e8-9318-34c577b6e234.png)

I would like to use this as a public gateway between my consumers & my internal Mesh Applications 

![image](https://user-images.githubusercontent.com/4345663/41866986-0ea1e62c-78b2-11e8-841f-62f23ad76cba.png)

## Possible Approach
One approach that I'm thinking of:
1. Deploy data store with volume (ie. Azure Files)
2. Deploy seed application
3. Deploy Kong gateway

Where step 1 & 2 are one step in deployment process and 3 is a seperate ARM/YAML template given you cannot "depend" on a job that has succeeeded or application.

## Additional Information
In case this could help, here is the [Helm chart for Kong](https://github.com/kubernetes/charts/tree/master/stable/kong)

**Comment by MikkelHegn** [comment]
Missed this @tomkerkhove - yes a script to do somethign, then the ARM deployment.

The concept sounds similar to what's the SetupEntryPoint (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-model-schema-elements#setupentrypoint-element) in Service Fabric Native applications today. We will look in to how this could be supported.

**Comment by tomkerkhove** [comment]
That's great, thank you!
