### ISSUE TITLE
az mesh deployment create --parameters does not have documentation 

### ISSUE THREAD

**Issue by oanapl** [Azure/service-fabric-mesh-preview#163]
az mesh deployment create has no help for parameters.

Arguments
    --no-wait                     : Do not wait for the long-running operation to finish.
    --parameters

**Comment by markheath** [comment]
would also be nice if there was an easier way to specify parameters when calling the azure CLI from powershell as it's really painful to properly escape the json. 

Something like
```
-param Key1=Value1 Key2=Value2
```
would be good

**Comment by andrewdmoreno** [comment]
@markheath I'm experiencing the pain with this as we speak. Do you have any pointers or gotchas you can pass along that you may have discovered in your troubles?

**Comment by anantshankar17** [comment]
Hello @andrewdmoreno/ @markheath 
We have updated the help strings of cli and have added couple of options to specify the parameters as shown below:
![image](https://user-images.githubusercontent.com/39825466/53551530-8755f480-3b5f-11e9-943a-ac2dc769b10b.png)
