### ISSUE TITLE
azure delete command cannot delete application deployed from VS

### ISSUE THREAD

**Issue by amenarde** [Azure/service-fabric-mesh-preview#180]
Deployed application to azure using visual studio made from https://review.docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-quickstart-dotnet-core?branch=pr-en-us-45221

On azure portal, when I try to delete from (MeshApplication/Overview/Delete), throws:
Operation name
Delete Applications
Time stamp
Wed Jun 27 2018 15:30:57 GMT-0700 (Pacific Daylight Time)
Event initiated by
t-anmen@microsoft.com
Error code
NoRegisteredProviderFound
Message
No registered resource provider found for location 'eastus' and API version '2018-02-01' for type 'applications'. The supported api-versions are '2018-03-01-privatepreview'. The supported locations are 'eastus, westus'.

This implies to me that the delete request is being generated with an old API version and subsequently being rejected.

**Comment by mattrowmsft** [comment]
This is fixed with today's portal deployment.
