### ISSUE TITLE
Failed to deploy hellow world app - resource deployment failure first time, second time, failed to find app error

### ISSUE THREAD

**Issue by raunakpandya** [Azure/service-fabric-mesh-preview#184]
C:\WINDOWS\system32>az mesh deployment create --resource-group raunakrg --template-file c:\Users\raunakp\hellowworld.json
If the deployment takes more than 10 minutes, then open up a new CLI window and run the following to get the status of your application deployment.
az mesh app show --resource-group <resource group name> --name <application name>
The output should point to the potential issue. If the “app show” cmd response does not have any errors listed, then it could just be that your image is taking long to download, rerun the az mesh app show command again after 5 minutes.
Deployment failed. Correlation ID: db6296fa-658b-43a4-9c34-e13086957c40. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'."
  }
}

C:\WINDOWS\system32>az mesh deployment create --resource-group raunakrg --template-file c:\Users\raunakp\hellowworld.json
If the deployment takes more than 10 minutes, then open up a new CLI window and run the following to get the status of your application deployment.
az mesh app show --resource-group <resource group name> --name <application name>
The output should point to the potential issue. If the “app show” cmd response does not have any errors listed, then it could just be that your image is taking long to download, rerun the az mesh app show command again after 5 minutes.
Deployment failed. Correlation ID: 712cc2a1-1346-4955-9907-36a268357641. {
  "error": {
    "code": "NotFound",
    "message": "Resource /subscriptions/13ad2c84-84fa-4798-ad71-e70c07af873f/resourcegroups/RAUNAKRG/providers/Microsoft.ServiceFabric/applications/HELLOWORLDAPP not found.",
    "details": [],
    "innerError": "Code: NotFound - System.Fabric.Wrp.Common.WrpException: Resource /subscriptions/13ad2c84-84fa-4798-ad71-e70c07af873f/resourcegroups/RAUNAKRG/providers/Microsoft.ServiceFabric/applications/HELLOWORLDAPP not found.\r\n   at System.Fabric.Wrp.ReliableDictionaryDataAccess.PersistedStore`2.<GetReadOnlyItemAsync>d__16.MoveNext() in D:\\agent_work\\1\\s\\src\\Common\\ReliableDictionaryDataAccess\\PersistedStore.cs:line 152\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.SeaBreeze.Actors.RealActorProxy`2.<InvokeMethodWithReturnValue>d__13`1.MoveNext() in D:\\agent_work\\1\\s\\src\\Actors\\RealActorProxy.cs:line 174\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.SeaBreeze.ApplicationManager.Operation.GetApplicationOperation`1.<ExecuteAsync>d__5.MoveNext() in D:\\agent_work\\1\\s\\src\\ApplicationManager\\Operation\\Applications\\GetApplicationOperation.cs:line 36\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Fabric.Wrp.Common.OperationBase`1.<RunAsync>d__48.MoveNext() in D:\\agent_work\\1\\s\\src\\Common\\OperationBase.cs:line 0"
  }
}

**Comment by ChackDan** [comment]
Please retry. The deployment issues for the most part are now fixed.
