### ISSUE TITLE
Clean up resources experience is buggy

### ISSUE THREAD

**Issue by novino** [Azure/service-fabric-mesh-preview#187]
az mesh app delete -g nachandr -n helloWorldApp is taking too long and not able to delete.
Subscription - SF Temporary subscription
Region - eastUS
resourceGroup - nachandr
time waited - more than 30 minutes
az cli version - 2.0.39
mesh version - mesh (0.7.0)

**Comment by VipulM-MSFT** [comment]
There was temporary issue with the service while in private preview. If you still encounter this, please re-open the issue with the full Resource ID and the time it happened.
