### ISSUE TITLE
Documentation on Mesh has code snippets related to linux

### ISSUE THREAD

**Issue by ashishnegi** [Azure/service-fabric-mesh-preview#188]
I have tried to fix one https://github.com/rwike77/azure-docs-pr/pull/17/commits/357de164b179f6fffc7a5362f0e3ce0ff076aff9
But there can be more issues.

**Comment by VipulM-MSFT** [comment]
This is already fixed in the published Service Fabric Mesh documentation. 

https://docs.microsoft.com/en-us/azure/service-fabric-mesh/

If not, please re-open the issue with the right link.
