### ISSUE TITLE
az mesh shows no resources, if the resource was created from Visual Studio

### ISSUE THREAD

**Issue by MikkelHegn** [Azure/service-fabric-mesh-preview#195]
Latest Visual Studio tooling is using the new namespace `Microsoft.ServicefabricMesh` and api version `2018-07-01-preview`. The Azure cli `az mesh` does not support this namespace and api-version and cannot query these resources.

The same will happen if you create a deployment from `az mesh `using the new namespace and api.

**Comment by mattrowmsft** [comment]
Everything should be on new namespace now.
