### ISSUE TITLE
CLI command validation for invalid resource group name is incorrect 

### ISSUE THREAD

**Issue by dkkapur** [Azure/service-fabric-mesh-preview#200]
![image](https://user-images.githubusercontent.com/2343218/42405338-0d51cc84-8149-11e8-9282-a62b737850bf.png)

In this command, I was missing the resourcegroupname, but the response is that the "system cannot find the file" which sounds more like there's an issue with the template file I'm pointing to, which is not the case.

**Comment by VipulM-MSFT** [comment]
The error is not coming from the CLI it is coming from the shell you are using. Try this

```
C:\Users\vipulm>dir <MyResourceGroupName
The system cannot find the file specified.
```
OR 
```
vipul@Azure:~$ az group deployment create -g <MyResourceGroupName> --template-uri https://sfmeshsamples.blob.core.windows.net/templates/helloworld/mesh_rp.linux.json
bash: MyResourceGroupName: No such file or directory
```
OR
```
vipul@Azure:~$ ls <MyResourceGroupName
bash: MyResourceGroupName: No such file or directory
```
