### ISSUE TITLE
Unable to delete Mesh app or parent resource group

### ISSUE THREAD

**Issue by mcollier** [Azure/service-fabric-mesh-preview#207]
I have an app that appears to be stuck in an "Updating" provisioning state with a status of "Invalid".  I am unable to delete the app using the `az mesh app delete` Azure CLI command (error is "Max retries exceeded with url: /subscriptions/xxxxxx/resourceGroups/coazure-sfmesh-helloworld/providers/Microsoft.ServiceFabric/applications/helloWorldAppWindows?api-version=2018-03-01-privatepreview (Caused by ResponseError('too many 504 error responses',))"

Using the Azure Portal and Azure CLI, I have tried to delete the resource group for this application.  Both seem to attempt to start to delete the resource group, but never complete (the group is never deleted).

**Comment by ChackDan** [comment]
@mcollier  - did you end up deleting the RG ?

**Comment by VipulM-MSFT** [comment]
@mcollier - we are closing this issue for now. If you do run in to it, please feel free to reopen.
