### ISSUE TITLE
Az CLI not working for "network show"

### ISSUE THREAD

**Issue by dkkapur** [Azure/service-fabric-mesh-preview#212]
This seems to be part of a known issue but putting it here so we can track and manage duplicates.

![image](https://user-images.githubusercontent.com/2343218/42483906-46cabddc-83a5-11e8-9385-01ba4cd8fa33.png)

Even though an app and a network is provisioned successfully, the resources don't show up in Portal or through CLI.

**Comment by mattrowmsft** [comment]
namespace issue which is fixed with latest stack of tooling.
