### ISSUE TITLE
Use the same port (internal port) for multiple services

### ISSUE THREAD

**Issue by SamirFarhat** [Azure/service-fabric-mesh-preview#213]
Why multiple Services cannot use the same port?
I have created a SFM App with two services. Each Sevice has one code package, each code package listens on a port, the same port. I have then published each port using the ingress configuration.
I was able to reach only one service. 
I have then modified the template so that the second service uses a different port, and then it worked.
Is this unsupported? 

Thanks

**Comment by ChackDan** [comment]
@SamirFarhat  - Layer 7 capabilities are in the roadmap.

**Comment by mattrowmsft** [comment]
This is now an option with gateway resources! Please reopen if you see any gaps.
