### ISSUE TITLE
Portal experience for networking

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#220]
What are the plans for the portal experience when it comes to Networking?

### Required features
- Overview of all applications that are part of the network
- List of all endpoints that are exposed, both externally & internally

### Nice-to-have features
- See the volume of traffic from an inbound part

**Comment by ChackDan** [comment]
We plan to have a much improved portal experience by Sept. the portal team walked though the mocks yesterday. The first wave would focus more on the manage experience.  If you would spare time to give us some early feedback, do email me.

**Comment by ChackDan** [comment]
It is not typical for us to share the mocks pubically, however if you are willing, I can ask the designers to have you be a part of the UI study on the mocks. That is what tom and a couple of others who wanted to help are doing.

If you are interested, email me chackdan@microsoft.com.
