### ISSUE TITLE
Provide endpoint validation for networks

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#221]
Would be good that there is some sort of endpoint validation when new networks are being added to ensure that port forwarding is setup correctly.

**Comment by mattrowmsft** [comment]
Are you thinking like the network endpoint should be able to specify some kind of heartbeat messages and then show status of those heartbeats?  Or something simpler which just shows whether any service endpoint exists on an application which is matched to the network l4config configuration?
