### ISSUE TITLE
SFM pricing page

### ISSUE THREAD

**Issue by SamirFarhat** [Azure/service-fabric-mesh-preview#227]
Is there any page describing the SFM pricing?

**Comment by tomkerkhove** [comment]
There is no pricing applied yet nor documented:
> Is there any cost associated to the preview?
> Currently, there are no charges for deploying applications or containers to the Azure Service Mesh public preview. However, in the next few months we will begin to charge for the resources you deploy at 50 percent of the cost when the service is generally available. Before we make the switch to charging you for the resources, we will publish another post on the Azure blog, so that you are aware of this change.
([source](https://azure.microsoft.com/en-us/blog/azure-service-fabric-mesh-is-now-in-public-preview/))

**Comment by SamirFarhat** [comment]
Thanks. I was aware of that on PP, but for Public preview, you have the answer.
