### ISSUE TITLE
Deploying through sfctl and the API

### ISSUE THREAD

**Issue by Pothulapati** [Azure/service-fabric-mesh-preview#228]
I've followed the documentation and was able to create a sf mesh application on Azure. The experience was really fluid. Cheers!

I also installed the service fabric run-time to run a local development cluster, Is there a way to deploy mesh applications to the local cluster from sfctl (as with the new application model, it is just a template.json to deploy applications). Through Visual Studio is the only way to deploy applications to local cluster now I think.

Is there any more information about the API that handles deploying mesh applications on a local or cloud deployed azure sf cluster, I'm sure it would open a lot of scope for extensibility if the API is documented. (Maybe a package manager for SF like helm?)
The future looks bright. :sparkler:

**Comment by VipulM-MSFT** [comment]
The SFCTL work is in progress. Today there is a PowerShell module that you can use to deploy to local cluster. This is the same module that VS uses @amanbha to provide details.

We are in the process of releasing the API documentation. The Swagger specification for the RP is published and Swagger for the Service Fabric Client APIs is in progress.

**Comment by amanbha** [comment]
@Pothulapati There is a PS module used by VS to deploy to local cluster which can be used to deploy to other Service Fabric clusters as well. This PS module makes REST calls to Service Fabric Http Gateway. Its available at C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Mesh\Scripts\PSModule. This currently supports unsecured clusters only and the usage might change in future as this is currently a preview module and provided to enable VS tooling experience..
Steps to use:
`Import-Module "C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Mesh\Scripts\PSModule\ServiceFabricHttpPSModule.dll"
Connect-SFCLuster <ClusterHttpGatewayEndpoint>
New-SFApplicationResource -ApplicationResourceName ApplicationResourcename -ResourceDescriptionFile ResourceDescriptionFilePath`

**Comment by VipulM-MSFT** [comment]
The REST API specification is published here: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/servicefabricmesh/resource-manager

**Comment by Pothulapati** [comment]
This look likes the spec for Azure resource manager. So, does the same spec for the local service fabric cluster? If yes what are the fields subscriptionid and resource group going to be? 
Thanks

**Comment by VipulM-MSFT** [comment]
The documentation for the Mesh RP is published here. https://docs.microsoft.com/en-us/rest/api/servicefabric/

The local cluster REST API specifications are in the process of being published.

**Comment by VipulM-MSFT** [comment]
[Mesh RP REST APIs](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfmeshrp-index)
[Mesh RP REST API Specs](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/servicefabricmesh/resource-manager)

[Service Fabric Client Resource APIs](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-index#service-fabric-resource-model)
[Service Fabric Client API Specs](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/servicefabric/data-plane/Microsoft.ServiceFabric/stable/6.3)
