### ISSUE TITLE
Visual Studio Tools for Service Fabric Mesh - Support for Linux

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#229]
Is there a timeframe for support for Linux services with the Visual Studio Tools for Service Fabric Mesh?

**Comment by VipulM-MSFT** [comment]
@raunakpandya, @dbreshears and @MikkelHegn

**Comment by MikkelHegn** [comment]
The only thing you cannot do today is debug the services in a Service Fabric cluster. You can debug the service outside a container, by changing the startup projects and launch profile. To publish, you only have to change the os type in the yaml files.

The missing pieces her is how to run SF on Linux on Windows, or how to have SF on Windows run Linux containers. We are still assessing the best path for that scenario.
