### ISSUE TITLE
Support for exploring state

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#234]
Given state will be stored in a volume, will we be able to browse the stored state in that volume?

It would be great to have a "State Explorer" that provides this capability for both development & operational reasons.

Kudos to @samneirinck for the idea.

**Comment by ChackDan** [comment]
I agree :).

**Comment by gkhanna79** [comment]
@tomkerkhove Which volume are you referring to and what state do you wish to view? Can you please elaborate?

**Comment by tomkerkhove** [comment]
@gkhanna79 I'm referring to reliable collection state and the corresponding volume.

**Comment by gkhanna79** [comment]
@tomkerkhove The VolumeDisk based upon reliable collections (i.e. SFvolumeDisk) looks like a regular disk that you can view using existing file exploration tools like Windows Explorer. Are you looking for something other than that?

**Comment by tomkerkhove** [comment]
I would need to see how the structure is - If it's straight forward then it's ok but if it's not a tool would be good.

**Comment by aloneguid** [comment]
@gkhanna79  @tomkerkhove SF volumes and reliable collections are not available in preview, how are you even using them?

**Comment by gkhanna79** [comment]
SFVolumeDisk will be part of SFMesh upcoming preview @aloneguid.

@tomkerkhove Can you please elaborate on the structure you refer to? SFVolumeDisk is a regular disk as far as OS is concerned and will look like any other disk.

**Comment by tomkerkhove** [comment]
> @gkhanna79 @tomkerkhove SF volumes and reliable collections are not available in preview, how are you even using them?

@aloneguid Not =)

@gkhanna79 	Reliable collections are glorified dictionaries, would I then have a folder which is the key with a file in it which is the value or?

**Comment by gkhanna79** [comment]
@tomkerkhove Not really. The disk is a block device, so that is what the dictionaries will have (blocks of data). The view, from a user standpoint, is not the dictionary entries but rather the disk made available to the storage stack.
