### ISSUE TITLE
Visual Studio tooling exposes secret

### ISSUE THREAD

**Issue by askew** [Azure/service-fabric-mesh-preview#235]
The Visual Studio tooling generates an ARM template that is used to publish the application to SF Mesh. This template has the parameter `registryPassword` of type `string`. This parameter needs to be `securestring` as the Container Registry password is currently revealed in plain text in the resource group deployment history.

**Comment by ChackDan** [comment]
Yes, this is only a point in time thing. we are adding support for "secret" resources, where you would be able to specify "inline" or "by ref" secrets. When using "by ref" the secret would be in KeyVault.

I will keep this issue open to track this to closure. Thankyou for reporting it.

**Comment by VipulM-MSFT** [comment]
@ChackDan before the secret support we should change the template to use securestring. @BigMorty

**Comment by ChackDan** [comment]
Makes sense.

**Comment by BigMorty** [comment]
We have made this change, it will be in the next refresh of the Visual Studio Mesh tools!

**Comment by BigMorty** [comment]
This has been fixed in the recent update to the Mesh tools. @askew - would you mind closing this issue please?

Thanks,
Mike
