### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#236]
Are there plans to provide a roadmap on what features are coming and an estimated delivery?

**Comment by MedAnd** [comment]
@tomkerkhove just had @ChackDan share some roadmap details in the discussion section of this post: https://disqus.com/home/discussion/thewindowsazureblog/azure_service_fabric_mesh_is_now_in_public_preview

Also asked this question via this issue: [State Storage Roadmap](https://github.com/MicrosoftDocs/azure-docs/issues/11905) but was closed as per comments...

**Comment by ChackDan** [comment]
@tomkerkhove  and @MedAnd  - give us some time. We will publish the features that are planned for this year soon. Like all engineering teams, we are also on a tight budget and so are now in the process of making painful cuts, so that we have features that are of great quality.

**Comment by andreujuanc** [comment]
Hi guys, @tomkerkhove @ChackDan 
Any update? :)
I don't usually comment on closed issues, but when I do I tag people. 😝

**Comment by ChackDan** [comment]
@deep  - Let us update the roadmap, so that customers know that we are evolving the app model to be more K8 ecosystem friendly and also evolving the serverless platform backend to support not only the evolved app model, but also Linux Functions...

**Comment by homeworryfree** [comment]
We're now in 2020.  The Preview came out in 2018.  Is this going to be one of those products that Microsoft never releases?  Based on your 2019 comment, it sounds like you will need to go through the whole prerelease process again?  I see your released version 4.0 recently, so I'm hopeful. Mesh sounds perfect for my needs, so I am seriously wondering.

**Comment by homeworryfree** [comment]
I'm using Visual Studio 2019, and I installed Docker and Service Fabric and Service Fabric Mesh, but I'm not seeing a Service Fabric Mesh extension for Visual Studio 2019, only Service Fabric Tools.  Will I need it?  I already uninstalled VS 2017, do I have to reinstall it?
