### ISSUE TITLE
Deployment fails without additional information

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#244]
While trying to deploy the script below it failed without giving any indication what the cause was.

How should I troubleshoot this? Couldn't find a way to get more information about this...

### Correlation Id
350115d9-9611-4426-9d71-3f96a8570620

### CLI Output
```shell
tom@Azure:~$ az mesh deployment create --resource-group containo-apps --template-uri https://containo.blob.core.windows.net/mesh-deployment/issues/244/service-fabric-mesh-orders-declaration.json
Deploying . . .
Please provide securestring value for 'ServiceBus.ConnectionString' (? for help):
Please provide securestring value for 'TableStorage.ConnectionString' (? for help):
Deployment failed
deployment correlation ID: 350115d9-9611-4426-9d71-3f96a8570620
application Containo-Orders deployment failed with None
To recieve additional information run the following to get the status of the application deployment.
az mesh app show --resource-group containo-apps --name Containo-Orders
Deployment Errors:
{
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'."
}

```

**Comment by tomkerkhove** [comment]
Anybody who can help with this? /cc @ChackDan

**Comment by tomkerkhove** [comment]
Thank you for checking this @mattrowmsft!

I tried this again in 2 new resource groups (East US & West Europe) but both failed unfortunately.

Correlation Id for EU deployment: `3ff47a82-86a1-4daf-ab43-240de7ede03d`

**Comment by tomkerkhove** [comment]
Any update on this @mattrowmsft?

**Comment by mattrowmsft** [comment]
@tomkerkhove  sorry about delay.  Sorry I missed this previously, there is a bug where we require tags on container images still.  There is a different bug that caused this failure to not get messaged back.  The messaging on this should improve within the next week.  Not requiring tags will take 2-3 weeks I think.

Can you try with image set to redis:4.0.11 or something similar?

**Comment by tomkerkhove** [comment]
No problem! I was just following up on this.

I've tried adding the image tag but it still fails.

### Deployment info
- **Correlation id:** `babb2836-fee5-4e79-8c6e-f4b3daaeb05d`
- **Template :** https://containo.blob.core.windows.net/mesh-deployment/issues/244/service-fabric-mesh-orders-declaration-v2.json

**Comment by mattrowmsft** [comment]
Containo-Orders-Cache service is referencing network under old namespace.  Sorry not having these details passed back makes this process way more difficult than it needs to be.  Fixes coming soon!

**Comment by tomkerkhove** [comment]
Wow good point, sorry for that! This fixed my issues, thanks for having a look @mattrowmsft!

**Comment by mattrowmsft** [comment]
Glad that worked, good news is that all these messages should have shown up in the statusDetails field of application. Fix should be rolled out soon!
