### ISSUE TITLE
Provide support for Virtual Kubelet

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#245]
Provide support for Virtual Kubelet so that we can run a hybrid workload between Kubernetes & Mesh.

This would allow existing customers that are using Kubernetes to run certain workloads in Mesh such as actor-based or stateful-based services.

**Comment by tomkerkhove** [comment]
And it's happening already, awesome! - https://github.com/virtual-kubelet/virtual-kubelet/tree/master/providers/sfmesh

**Comment by MikkelHegn** [comment]
Did you try it out and have any feedback?

**Comment by tomkerkhove** [comment]
I did not give it a try before, sorry!

**Comment by tomkerkhove** [comment]
I was going to give this one a spin but it looks like there is no way to run it inside a cluster already.

Are there plans to provide more guidance on how to run this? This is a great example of the ACI team - https://github.com/virtual-kubelet/virtual-kubelet/tree/master/providers/azure#deployment-of-the-aci-provider-in-your-cluster

**Comment by ChackDan** [comment]
@dkkapur can you follow up on this to provide the guidance.

**Comment by tomkerkhove** [comment]
Bump

**Comment by tomkerkhove** [comment]
Bumping again - What's the status here?

**Comment by mattrowmsft** [comment]
Virtual Kubelet is a means to serverless, so we are very closely engaged with that team how to leverage the best of Mesh to help the project succeed.  I think the interesting part will be how much we can help within the existing definition of a Virtual Kubelet and how much will come as part of expanding the VK spec.

**Comment by tomkerkhove** [comment]
Actually you can just build your own provider based off of that which is already there - But there seems to be that much progress with it - https://github.com/virtual-kubelet/virtual-kubelet/tree/master/providers/sfmesh

Having 1st class citizen support would be tremendous and make it easier for folks to use Service Fabric Mesh.

For me personally, the sweet spot is to run on Kubernetes by default and run services that require statefulness, or other Mesh features, on Mesh via Virtual Kubelet.
