### ISSUE TITLE
Using VPN Gateway or Equivalent with Service Fabric Mesh

### ISSUE THREAD

**Issue by heymega** [Azure/service-fabric-mesh-preview#259]
Is it possible for Service Fabric Mesh to use Azure VPN Gateway in order to communicate with an on-prem network?

Some of our services are currently relying on Anti-Corruption Layers.

I've noticed that Service Fabric Mesh's network resource isn't the same as the Virtual Network that you use to setup a VPN Gateway.

**Comment by ChackDan** [comment]
"Bring you own Vnet" capability is planned to come in around OCT timeframe. At that time the network resource will have configurations that will allow for this capblity to be requested.

You are right, the current Mesh network resource is not the same as the networking capabilities that  Azure Networking provides.  We are working with Azure networking to enable BYO-VNET integration. The current Mesh networks will also evolve to supprot layer 7 capabilities, like mulitple ingress for services etc. We will also provide an isolated application scoped VNET as well.

**Comment by heymega** [comment]
That's sounds awesome!

Keep up the good work Chacko
