### ISSUE TITLE
Application is loosing IP address

### ISSUE THREAD

**Issue by smereczynski** [Azure/service-fabric-mesh-preview#260]
Hi,
I have deployed a Hello World sample (on Linux): https://github.com/Azure-Samples/service-fabric-mesh/tree/master/templates/helloworld

Deployment was made few hours ago. Now, on other machine I was trying to connect to this service. I did not made any note with public IP, so I went to CLI and... nothing:

`az mesh app show --resource-group meshTest --name helloWorldApp`

    {
      "debugParams": null,
      "description": "Service Fabric Mesh HelloWorld Application!",
      "diagnostics": null,
      "healthState": "Ok",
      "id": "/subscriptions/d8207ac4-c426-49b0-8395-3f197ed7a82e/resourcegroups/meshTest/providers/Microsoft.ServiceFabricMesh/applications/helloWorldApp",
      "location": "eastus",
      "name": "helloWorldApp",
      "provisioningState": "Succeeded",
      "resourceGroup": "meshTest",
      "serviceNames": [
        "helloWorldService"
      ],
      "services": null,
      "status": "Ready",
      "statusDetails": null,
      "tags": {},
      "type": "applications",
      "unhealthyEvaluation": null
    }

**Comment by mattrowmsft** [comment]
You need to do a show on the network to get the IP address.

**Comment by smereczynski** [comment]
Ha! Bingo! To be honest, I think it should be in the app also (probably there is a milion reasons to not do that) because people are looking for it there. Anyway: THANK YOU!

**Comment by smereczynski** [comment]
Even reference to the network in an output will be great - like in VM. Seeing network in reference I will try to check (like with NIC in VM).
