### ISSUE TITLE
Linux Environment variables with '=' are not passed correctly

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#264]
_**Disclaimer:** This is initial thinking based on what I've seen but it might be a side-effect_

I was running my [tomkerkhove/containo](https://github.com/tomkerkhove/containo) sample on Service Fabric Mesh which uses Azure Storage but suddenly it started throwing the following exceptions:
> FormatException: Settings must be of the form "name=value".
Microsoft.WindowsAzure.Storage.CloudStorageAccount+<>c.<Parse>b__97_0(string err)

### Analysis
When running this locally with the same environment variables everything went fine so I had a feeling that the environment variables were not passed correctly.

When checking the service configuration with `az mesh service show --name Containo-Orders-API --app-name Containo-Orders --resource-group containo-apps` it shows me this:
![image](https://user-images.githubusercontent.com/4345663/44253209-1a03f700-a1ff-11e8-8d60-3fd3c33fdd1f.png)

The service is deployed correctly and the connection string is valid.

Given I cannot get the code package logs (#263) nor get replica list (#115) I changed my code to throw an explicit exception which track the connection string that was read. ([code](https://github.com/tomkerkhove/containo/blob/mesh-issues-env-variables/src/Containo.Services.Orders.Storage/Repositories/OrdersRepository.cs#L27) | ([docker image](https://hub.docker.com/r/tomkerkhove/containo.services.orders.api.temp/)))

When running this adapted code it shows me that the following environment variable was used:
>ApplicationException: Connection string - DefaultEndpointsProtocol
Containo.Services.Orders.Storage.Repositories.OrdersRepository..ctor() in OrdersRepository.cs, line 27

### Repro
It is documented here how you can deploy everything - https://github.com/tomkerkhove/containo/tree/master/deploy#deploying-containo-on-azure-service-fabric-mesh

Given the limitation of parameters and the nature of the issue I suggest to use [this template](https://containo.blob.core.windows.net/mesh-deployment/issues/244/service-fabric-mesh-orders-declaration-v3.json) which uses a temporary docker image which catches the exception and shows the connection string when calling `http://40.118.7.65:1337/api/foo/orders/bar`

**Comment by tomkerkhove** [comment]
In order to fully isolate everything, I've updated the troubleshoot image with an [environment variable controller](https://github.com/tomkerkhove/containo/blob/mesh-issues-env-variables/src/Containo.Services.Orders.Api/Controllers/EnvironmentController.cs) which just reads the value and gives it to the client.

Deployed this new version with the same template which you can try it here: http://51.145.135.185:1337/api/environment/TableStorage_ConnectionString

I will roll the secret afterwards so don't bother :)

**Comment by tomkerkhove** [comment]
Tagging @ChackDan as this is a pretty crucial bug at the moment

**Comment by ChackDan** [comment]
@BharatNarasimman  and @VipulM-MSFT  Could you please follow up on this

**Comment by mattrowmsft** [comment]
FYI I think we have identified issue. B\c of where the bug is in the stack it will probably take 1-2 weeks to get fix rolled out.  If it's possible in your specific scenario to split the env variable value around the '=' character that could work for now.

**Comment by tomkerkhove** [comment]
Thanks for having a look - I'll wait until the fix is there and test it then. Feel free to let me know if I can help any further!

**Comment by ChackDan** [comment]
Thankyou Tom. Will do .

**Comment by tomkerkhove** [comment]
Is there an update on this?

**Comment by mattrowmsft** [comment]
The next major update will switch Linux container runtime and we have verified that it doesn't have same issues.  Tune in to Ignite.

**Comment by tomkerkhove** [comment]
I've tried this again and seem to be hitting the same issue. Is there an update on this @mattrowmsft?

**Comment by tomkerkhove** [comment]
@ChackDan Was 6.4 already released or should I wait a bit longer?

**Comment by tomkerkhove** [comment]
Thanks for the update, what is the estimated date for this fix?

The workaround could work but would still be good to have a fix for this as it will not always be a secret nor is passing base64 values ideal.

**Comment by tomkerkhove** [comment]
I can confirm that this has not been fixed with the refresh. Any ETA for this?

**Comment by tomkerkhove** [comment]
Bumping - What's the status here?

**Comment by mattrowmsft** [comment]
I don't think there will be any switch to Kata runtime at this point solely for the reason of fixing this bug.  For now I think Vipul's suggestions above are the best workarounds.  It's a bit of a pain for black box containers where you can change logic to read from file (via settings) or decode base64 environment string.  Eventually we would be moving away from Clear container runtime (think summer), but presently Kata is seen as too small of a step to invest in support.
