### ISSUE TITLE
.NET Framework deployment Failed

### ISSUE THREAD

**Issue by jjcollinge** [Azure/service-fabric-mesh-preview#27]
I tried deploying full fat .NET framework using the following configuration:

```json
{
    "instanceCount": 2,
    "containerGroup": {
        "containers": [{
                "name": "sbz-quickstart-app",
                "properties": {
                    "image": "microsoft/dotnet-framework:4.7.1-windowsservercore-1709",
                    "resources": {
                        "requests": {
                            "cpu": 1,
                            "memoryInGb": 1.5
                        }
                    },
                    "ports": [{
                        "port": 80
                    }]
                }
            }
        ],
        "osType": "Windows",
        "ipAddress": {
            "type": "Public",
            "ports": [{
                "protocol": "tcp",
                "port": "80"
            }]
        }
    }
}
```
This resulted in: ` "provisioningState": "Failed"` - no additional error details available.
I tried 1709 and ltsc2016 just to check it wasn't a compatibility issue.
The image is several GB, is this a potential timeout issue whilst pulling the image or potentially the resources are too constrained?

I ran the image locally, it took a ~15 mins to start but did run OK.

**Comment by mkosieradzki** [comment]
I was able to run this image on SFM - it took around 14-16 minutes to start, but it works correctly now. I am surprised that this base image is not cached somewhere closer... :-(

**Comment by mattrowmsft** [comment]
this should be significantly faster now
