### ISSUE TITLE
No Content in Mesh Code Container Logs

### ISSUE THREAD

**Issue by johnnyhuy** [Azure/service-fabric-mesh-preview#271]
Greetings,

I've followed this [Set up your Windows development environment](https://docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-howto-setup-developer-environment-sdk#build-a-cluster) guide to deploy a generic application to my local cluster.

Using the template from the Visual Studio plugin, the app properly launches in my browser. However, I can't seem to find container logs other than the debug output from the IDE. I would assume logs are present in the SF cluster manager or `sfctl` commands (as mentioned [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-containers-view-logs)).

### Logs are shown in the debug output

![image](https://user-images.githubusercontent.com/27847622/44898452-50cf2680-ad42-11e8-9417-7bf1156ac78d.png)

### Missing container logs from both `sfctl` and SF cluster manager

![image](https://user-images.githubusercontent.com/27847622/44898606-c3400680-ad42-11e8-93ca-379933a623da.png)

![image](https://user-images.githubusercontent.com/27847622/44898420-31d09480-ad42-11e8-86f8-0fc3dcc2e9c6.png)

I've also launched a Mesh App to Azure Portal and I seem to get the same `"content": ""` JSON response with the following command:

```bash
az mesh code-package-log get --debug --resource-group <some resource group> --application-name TestWebApp --service-name TestWebAppService --replica-name 0 --code-package-name TestWebAppCode
```

I'm wondering if this is the expected behavior of the containers not showing anything their logs 🤔

Further adding to the question, if I were to just use Powershell scripts to deploy my Mesh app how do I view diagnostic logs of the running container?

## Update 03/09/18

I was able to deploy my application locally and found out that code package logs appear for a **short period** of time before disappearing. I would assume that logs get flushed after a container terminates on an error.

**Comment by MikkelHegn** [comment]
Fro dead containers logs - see here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-containers-view-logs#access-the-logs-of-a-dead-or-crashed-container

Based on your update, I'm not clear if you are still not seeing the logs from a consistent running container either locally or in Mesh? Can you please clarify - thanks :-)

@srrengar to comment on availability of dead container logs in Mesh in Azure.

**Comment by srrengar** [comment]
Currently we don't offer a way to grab crash dumps or dead container logs. This is forthcoming.

**Comment by johnnyhuy** [comment]
Hey guys,

I was always able to view logs from a running container on both in a local cluster and Mesh. Though it’s fairly tricky to catch dead container logs.

I’ve come to the conclusion to use a cluster instead. However, I’m guessing we’ll be using something similar to the Service Fabric explorer to diagnose container logs?

**Comment by srrengar** [comment]
Yes there will be an experience in the portal for this
