### ISSUE TITLE
Multiple networks associated with a single service

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-mesh-preview#289]
I am trying to deploy SFM application with service connected to multiple networks (I am experimenting with micro-segmentation until Service Mesh is supported in SFM).

What I am observing is a GatewayTimeout. Is this a supported scenario? Is it going to be supported in next preview?

**Comment by mattrowmsft** [comment]
This still has to be one to one between networks and services.  I think there is validation coming with the next release to make this more obvious.  Once the isolated networks/gateways demoed at Ignite are released, then scenarios like this will start to light up.

**Comment by mkosieradzki** [comment]
@mattrowmsft Thank you so much! I see it now. This is pretty awesome solution - I see how to do 90% of Service Mesh features now using gateways!
