### ISSUE TITLE
Question: How to gracefully shutdown?

### ISSUE THREAD

**Issue by aloneguid** [Azure/service-fabric-mesh-preview#291]
In "classic" Service Fabric services receive cancellation token request so they know they have to shutdown gracefully. Provided that all we have now is `static void Main(string[] args)` how would service gracefully shutdown?

**Comment by MikkelHegn** [comment]
Your container will receive a SIGTERM, so hooking in to the event .NET raises would be the equivalent.
A few references: https://stackoverflow.com/questions/38291567/killing-gracefully-a-net-core-daemon-running-on-linux and https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.processexit?view=netcore-2.0

**Comment by aloneguid** [comment]
Thank you, tried and works for me.
