### ISSUE TITLE
Provide information about runtime version

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#293]
This is a bit of a controversial request but sometimes it is being mentioned that feature X is coming with version Y, but how does one see the version of runtime running your app?

Are there plans to display this in portal/via CLI?

Could be something like `az mesh app version --name foo --resource-group bar`.

**Comment by mattrowmsft** [comment]
For most features, this is an artifact of Mesh and SF being developed so closely together that it is hard for us to remember to use the correct nomenclature (ie 6.4 is actually 2018-09-01-preview api version).

There are some features which aren't tied to an api verison.  Container image caching is a recent example.  Where during an interim period, performance of the environments that you are deploying in might differ.  For this reason, I could see some properties of the runtime environment being exposed.
