### ISSUE TITLE
SfSbzYamlMerge.exe disappeared

### ISSUE THREAD

**Issue by rdiazconcha** [Azure/service-fabric-mesh-preview#299]
After upgrading the ASF Mesh SDK to the latest version (3.3.617.9590) using the Web PI, the SfSbzYamlMerge.exe file was deleted from the C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Mesh\SfSbzYamlMerge folder.  The rest of the files were there, just the .exe was deleted (!?).

I fixed it by uninstalling / reinstalling the SDK.

**Comment by aloneguid** [comment]
same problem here, thanks for the tip, worked after reinstalling

**Comment by markheath** [comment]
same here

**Comment by raunakpandya** [comment]
Sorry to hear that. We are investigating this.

**Comment by julipur** [comment]
any update on this issue?

**Comment by anantshankar17** [comment]
This was fixed in the previous CU release. Kindly retry & let us know.
