### ISSUE TITLE
Service Fabric Reliable Disk demo project execution fails

### ISSUE THREAD

**Issue by Pothulapati** [Azure/service-fabric-mesh-preview#301]
I tried running the service fabric reliable disk demo as per the [doc](https://docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-howto-deploy-app-sfreliable-disk-volume) , The command took a lot of time to execute and still the provisioning state is shown as running. I tried running it again, in a different resource group. The deployment failed with the following error. 

```json
Deployment failed. Correlation ID: fe30ad3e-8fe7-4ab6-9fda-6f4c07f04847. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "ClusterAllocationFailed",
        "message": "Cluster allocation failed.",
        "details": []
      }
    ]
  }
}
````

**Comment by heymega** [comment]
Going off Chacko's tweet earlier, they are still rolling out the changes across resource locations.

https://blogs.msdn.microsoft.com/azureservicefabric/2018/12/04/service-fabric-mesh-preview-refresh-release/

If you run this command it will show which locations have the update.

```Get-AzureRmResourceProvider -ProviderNamespace "Microsoft.ServiceFabricMesh" | ? {$_.ResourceTypes.ResourceTypeName -eq "gateways" } | % { $_.ResourceTypes.Locations}```

I've just executed that command and `East Asia` is the only resource location that's been updated.

Try running the demo against a resource group in that location and see if you get the same issue.

**Comment by raunakpandya** [comment]
I would suggest just wait for it to roll out in regions.. It should work post that.

**Comment by raunakpandya** [comment]
@Pothulapati - Are you still facing issue here?

**Comment by Pothulapati** [comment]
@raunakpandya - I tried it again. The command shows **running** for like half an hour and still shows the same. When I try to see the status of the deployment it is shown as running, but when I browse the **ipAddress** given, the site isn't responding.

Willing to share any other details if needed.
Thanks

**Comment by Pothulapati** [comment]
After a lot of time, It failed with the following error
```
Deployment failed. Correlation ID: 43b3192b-9645-4f04-becc-20bb4b142726. {
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource provision operation did not complete within the allowed timeout period. Please see https://aka.ms/arm-deploy for usage details."
  }
}
```

**Comment by raunakpandya** [comment]
@mattrowmsft - Any ideas?

**Comment by mattrowmsft** [comment]
@Pothulapati we are taking a look.

**Comment by mattrowmsft** [comment]
There was an error in our configuration for these clusters which caused a bunch of "bad" clusters to enter our pool.  These have been purged out, and the configuration error and the detection miss fixed.  Please try again now and it should work.

**Comment by Pothulapati** [comment]
@mattrowmsft Awesome, It works!

Thanks. :+1:
