### ISSUE TITLE
The provided location 'westeurope' is not available for resource type 'Microsoft.ServiceFabricMesh/gateways'. List of available regions for the resource type is 'eastasia'.

### ISSUE THREAD

**Issue by guibirow** [Azure/service-fabric-mesh-preview#303]
I tried to deploy the template from [this ](https://github.com/Azure-Samples/service-fabric-mesh/blob/master/templates/counter/counter.sfreliablevolume.linux.json) sample and i've got the following error:

`The provided location 'westeurope' is not available for resource type 'Microsoft.ServiceFabricMesh/gateways'. List of available regions for the resource type is 'eastasia'.`

But the tempalte says the only avilable regios are westus, eastus, westeurope.

Might be related to the same issue reported on https://github.com/Azure/service-fabric-mesh-preview/issues/301

**Comment by SamirFarhat** [comment]
This is due the last refresh i think. The Gateway resource type is only available in eastasia

**Comment by aloneguid** [comment]
Not anymore 
![image](https://user-images.githubusercontent.com/3155189/49617505-bb7ca780-f9ac-11e8-9096-fcd17d12563e.png)

**Comment by guibirow** [comment]
Closing down this issue as the regions has been upgraded with new resources
