### ISSUE TITLE
Mesh Resources not visible in azure portal resource group blade, only Applications

### ISSUE THREAD

**Issue by guibirow** [Azure/service-fabric-mesh-preview#305]
Currently, when Mesh resources are deployed to azure, only Applications are visible in the Resource Group View.

![image](https://user-images.githubusercontent.com/943026/49539171-f86d6f00-f8c4-11e8-963d-f9324b6877ff.png)

But when the Resource Group is pinned to the dashboard, is possible to see the missing resources!

![image](https://user-images.githubusercontent.com/943026/49539206-0ae7a880-f8c5-11e8-98c0-1d8b658ab535.png)
 

Not the same as #203 or #195

**Comment by BigMorty** [comment]
Check the "Show hidden types" checkbox and you will see the Network and Gateway resources as well.

**Comment by guibirow** [comment]
Thanks, very tricky

**Comment by BigMorty** [comment]
😉
