### ISSUE TITLE
resource created in different region is not listed in az mesh CLI

### ISSUE THREAD

**Issue by guibirow** [Azure/service-fabric-mesh-preview#306]
If I create a mesh resource in a diferent location than the resource group, when I try to list the resources from` az mesh <resourcetype> list --resource-group name` no results are shown.

Steps to reproduce:
Create a resource group named "**mesh**" and Location "**westeurope**"
Deploy the network resource on  "**eastus**" location within the  "**mesh**" resource group

Once deployment complete, run the command to list the networks:
`az mesh network list --resource-group mesh`

No resources will be listed

**Comment by jeffj6123** [comment]
was the deployment for the network successful? Also are you available to view the network within portal?

**Comment by guibirow** [comment]
Created successfully and visible in the Portal

**Comment by jeffj6123** [comment]
can you give the version of the mesh extension are you using? You can check using az extension list

**Comment by guibirow** [comment]
Closing this as I have updated the `az mesh extension` after raised this ticket and tried now to reproduce and is not facing the same errors

Thanks @jeffj6123
