### ISSUE TITLE
The Microsoft.ServiceFabricMesh/secrets is a Readonly resource

### ISSUE THREAD

**Issue by SamirFarhat** [Azure/service-fabric-mesh-preview#313]
During a deployment, i have updated the secret value of a secret.
I received the error message during the deployment of Microsoft.ServiceFabricMesh/secrets resources.

"error": {
    "code": "BadRequestWithReason",
    "message": "Request is invalid. Reason Secret version value is a readonly property.",
}

What do we need to do when updating the secret value ?

**Comment by guibirow** [comment]
I think this is an expected behavior. In the docs, it says:

> The name of the value is typically the version identifier. Once created the value cannot be changed.

I assume it follows the same approach of KeyVault, where each new value get a new version.
So you would have:

```
{
  "name": "v1",
  "properties": {
    "value": "mongodb://contoso123:0Fc3IolnL12312asdfawejunASDF@asdfYXX2t8a97kghVcUzcDv98ha.."
  }
}
```

Then :

```
{
  "name": "v2",
  "properties": {
    "value": "mongodb://abcdefg:0Fc3IolnL12312asdfawejunASDF.."
  }
}
```

**Comment by jeffj6123** [comment]
You can not change an existing secret value. @guibirow is correct, you should be creating a new version with the new secret value you want to use.

**Comment by SamirFarhat** [comment]
Thanks for you guys
