### ISSUE TITLE
The web app hosted in service fabric mesh is unable to make HTTP requests to another web api hosted as a stateless service in the same cluster

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/service-fabric-mesh-preview#326]
The following simple architect is in place:
1) A very simple angular web app hosted as a SF mesh in the local cluster which collects two piece of from the UI client app and submits to a backend web api.
2) The backend web api is a non-mesh stateless service fabric application which receives those two pieces of information to process them. 
3) Both SF mesh and the non-mesh SF stateless service are hosted on the same local cluster whose mode is "Mesh 1 Node".

The SF mesh application uses ```System.Net.Http.HttpClient``` instance to send POST requests in either of the following formats that I tried:

http://{computername}.{domainname}:24000/api/mycontroller/myaction

In this case the error message of **No such host is known.** is produced with the following stack trace:

> at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Polly.Retry.RetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory, Boolean continueOnCapturedContext) in C:\projects\polly\src\Polly.Shared\Retry\RetryEngineAsync.cs:line 0
>    at Polly.Retry.RetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory, Boolean continueOnCapturedContext) in C:\projects\polly\src\Polly.Shared\Retry\RetryEngineAsync.cs:line 65
>    at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

Replacing {computername}.{domainname} with **localhost** and make the URL look like http://localhost:24000/api/mycontroller/myaction results into the error message of **No connection could be made because the target machine actively refused it.** . Even replacing **localhost** with **127.0.0.1** resulted into the same issue.

**Comment by guibirow** [comment]
SF Mesh applications are deployed on Networks, that technically are Container Networks, when two SF mesh applications are deployed on different networks, they should not see each other.

In your case, the non SF is in a different network, this is likely the reason to be rejecting the access. It might be possible to change the network model for the mesh networks, but I didn't find any docs to prove that. In the standard SF cluster you can, might worth checking it [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-networking-modes) to see if the same applies to mesh.

A side note I would Add, Local cluster allow you to deploy both(Mesh and non mesh) applications on same cluster, but you won't be able to do it in SF Mesh in azure. You might be able to do on standard SF cluster tough.

**Comment by raunakpandya** [comment]
That's mostly correct. The only thing, the one box mesh cluster the default is not open but a different private NAT network. This network would be different from the network your non Mesh application is on.

**Comment by raunakpandya** [comment]
Please feel free to reactivate if you still have some queries on the same.
