### ISSUE TITLE
Pricing Clarification

### ISSUE THREAD

**Issue by kentcb** [Azure/service-fabric-mesh-preview#354]
Hi,

I understand that pricing for SFM is far cheaper - even free - during preview. However, I want to get some clarity on how pricing might look once it's out of preview. I'd hate to put in a bunch of effort porting to SFM only to find out it's more expensive than SF.

I heard somewhere that it will effectively bill using [Azure Container Instances pricing](https://azure.microsoft.com/en-us/pricing/details/container-instances/). Is this true? If so, what does this _mean_ for services? Typically, a containerized microservice won't exit - it will sit idle until it receives a message it needs to deal with. Will the SFM pricing model charge for that idle time or not?

Sorry if this has been answered already - I can't find any detailed information on this.

**Comment by dkkapur** [comment]
@kentcb - what you've heard about billing matching that of ACI is currently still true. The model prices based on container uptime, which means if the container is up and running, regardless of whether or not it is "doing work" as defined by how you architect your application, it will be charged based on the CPU and memory utilization. You could spin up containers only when required if needed, but in that case your orchestration will either be running in Mesh (which will be charged), or elsewhere (in which case ACI could be a good fit for you to run in production today).
