### ISSUE TITLE
Can I deploy services independently to Azure Service Fabric Mesh?

### ISSUE THREAD

**Issue by julipur** [Azure/service-fabric-mesh-preview#360]
Can I deploy services independently to an Azure Service Fabric Mesh application, or do I have to deploy all the services all the time? 

If all the services have to always be deployed, this seems like a limitation that won't allow separate teams, building different services, to work effectively. 

If there is a way, please let me know. I see the arm deployment will remove already deployed services if I only provide one of my services in the template.

**Comment by tomkerkhove** [comment]
You have to deploy all services given application is your unit of deployment as far as I know.

**Comment by julipur** [comment]
Thanks @tomkerkhove, that is the conclusion I have reached as well. Thank you.
