### ISSUE TITLE
sfvolumedisk plugin error on docker

### ISSUE THREAD

**Issue by andreujuanc** [Azure/service-fabric-mesh-preview#366]
Hi, 

Somehow we all at work cannot start docker with windows containers (linux works fine) and we see entries like this in our eventviewer: 

`[23:02:01.168][WindowsDaemon  ][Warning] Error restoring volume [error=error while checking if volume "sfvol-258b1a7d-4262-4dd9-9330-ce9900fbe49b" exists in driver "sfvolumedisk": error looking up volume plugin sfvolumedisk: legacy plugin: Post http://mymachinename:19101/Plugin.Activate: dial tcp [fe80::f1b2:3b41:1f91:52be%Wi-Fi]:19101: connectex: No connection could be made because the target machine actively refused it. driver=sfvolumedisk volume=sfvol-258b1a7d-4262-4dd9-9330-ce9900fbe49b]`

What can we do? We have tried almost everything,including uninstalling/reinstalling almost all software, except windows itself.

Can we somehow remove that sfvolumedisk plugin without docker cli? where is the plugin installed?

**Comment by mevora-msft** [comment]
Plugin file is @ "C:\programdata\docker\plugins\sfvolumedisk.json". Do you have any application using sfvolumedisk?

**Comment by andreujuanc** [comment]
Some of my teammates have observe similar issues than this, and for now the only solution they have is to reinstall docker and mesh. 
I will close this since it's hard to repro, but just keep track of it internally, since it's hardly a one of thing.
