### ISSUE TITLE
Partition is below target replica, node is stuck

### ISSUE THREAD

**Issue by mtalhaoui** [Azure/service-fabric-mesh-preview#368]
I'm trying to run a service fabric mesh applicaton locally in vs 2017, but as soon as the application is build I get some errors and warnings in the service fabric explorer. I am not able to run a hello world application.

Has anybody run into the same issue?

'System.FM' reported Error for property 'State'.
Partition is below target replica or instance count.
fabric:/Application2/Console1 1 1 d4f26725-aac7-4d82-a803-d442f78101f6
  N/P InBuild _Node_0 132042979063713078

'System.RAP' reported Warning for property 'IStatefulServiceReplica.ChangeRole(P)Duration'.
The api IStatefulServiceReplica.ChangeRole(P) on node _Node_0 is stuck. Start Time (UTC): 2019-06-06 12:31:51.604.

**Comment by aloneguid** [comment]
Does the issue persist when you remove the application?

**Comment by mtalhaoui** [comment]
As soon as the application is closed, it goes away.

**Comment by aloneguid** [comment]
Can you see it running in local Docker without issues?

**Comment by mtalhaoui** [comment]
I have tried: docker ps/docker container ls and and they don't display anything.

**Comment by aloneguid** [comment]
I had this sometimes, which is understandable in preview. Usually it goes away if I right-click and "remove mesh resources" 
![image](https://user-images.githubusercontent.com/3155189/59034995-42c7ac80-8864-11e9-9d18-f7d37c6b6357.png). Also try to drop all SF related docker containers.

**Comment by mtalhaoui** [comment]
I have removed the Mesh App Resources. I have removed all the docker containers with the following command: docker system prune.

Now it seems I have an extra error message:

'System.Hosting' reported Error for property 'CodePackageActivation:Console1:EntryPoint:132042976053925389'. There was an error during CodePackage activation.System.Fabric.FabricException (-2147017731) Failed to start Container. ContainerName=sf-5-48102e82-f9dd-419b-81f9-09f9cba20f15_8b3651e9-6139-4287-a5b3-1bba66d9a1d1, ApplicationId=SingleInstance_3_App5, ApplicationName=fabric:/Application2. DockerRequest returned StatusCode=NotFound with ResponseBody={"message":"network servicefabric_nat not found"}
--

**Comment by aloneguid** [comment]
I think you might need to re-create Mesh cluster as it adds docker networking component which is gone after prune.

**Comment by mtalhaoui** [comment]
I have removed the Local Cluster and created a new Mesh 1 node. 

I still have the same issue.

**Comment by mtalhaoui** [comment]
I have tried to use 'reset local cluster' and this seems to have solved the issue caused by the 'docker system prune' command. I now have the original issue again: partition is below target replica.

It appears the issue was not solved by this.

**Comment by mtalhaoui** [comment]
I've managed to solve this issue.

The problem was in my installation of vs 2017. The installation was seperated over 2 hdd's.
