### ISSUE TITLE
Insufficent Capacity - AustraliaEast, AustraliaSouthEast, SouthEastAsia, WestUs, EastUs, WestUS2

### ISSUE THREAD

**Issue by MickBadran** [Azure/service-fabric-mesh-preview#372]
Hi folks - just trying to deploy a couple of examples from the Samples/Templates folder - try Helloworld
(linux flavour)

Deployments all fail with insufficent capacity - try again or pick another region.

Q. How can I tell the SFMesh capacity of a region before I deploy?

**Comment by MickBadran** [comment]
Hi guys if we can this running I'd love to use this tech in a Bank I'm working at.

Not sure what the status is here on this tech.

Can someone please assist

Cheers,

Mick.

**Comment by mattrowmsft** [comment]
WestUS, EastUS, WestEurope, EastAsia for now.

**Comment by MickBadran** [comment]
thanks
