### ISSUE TITLE
Can not start Service Fabric Mesh anymore after docker upgrade

### ISSUE THREAD

**Issue by jellebens** [Azure/service-fabric-mesh-preview#377]
Upgraded to Docker for Windows 2.1.0.0
... It seems its not able to create the volume plugin anymore

Waiting for fabric:/System/NamingService to be ready. This may take a few minutes...
fabric:/System/NamingService is ready now...

Deploying Addon Service:AzureFilesVolumePlugin in the cluster...
PS>TerminatingError(Remove-Item): "An object at the specified path C:\Users\JELLE~1.BEN does not exist."
>> TerminatingError(Remove-Item): "An object at the specified path C:\Users\JELLE~1.BEN does not exist."
>> TerminatingError(Remove-Item): "An object at the specified path C:\Users\JELLE~1.BEN does not exist."
An object at the specified path C:\Users\JELLE~1.BEN does not exist.

**Comment by jellebens** [comment]
Fixed it 
-------------------------
uninstalling docker
Uninstall hyperv
uninstall service fabric and mesh
reinstalled docker 2.0.0.3
installed all the rest again

**Comment by anantshankar17** [comment]
Probably the HyperV VM whichis created by docker was busted. Since this is not an SF issue, closing it.
