### ISSUE TITLE
Service Fabric mesh on existing service fabric cluster

### ISSUE THREAD

**Issue by mandarsudame** [Azure/service-fabric-mesh-preview#384]
Is it possible to use Mesh applications on an existing Service Fabric cluster created using ARM?

**Comment by tomkerkhove** [comment]
If you mean use the same specification with "Mesh applications" then I think that is correct.

Adding @dkkapur who might know

**Comment by mandarsudame** [comment]
The cluster API on port 19080 returns 500 on a PUT mesh application request as given [here](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-meshapplication_createorupdate#applicationresourcename)
Used the same path as given in the link.
