### ISSUE TITLE
Service Fabric Mesh CANCELLED, Replaced by AKS! 

### ISSUE THREAD

**Issue by joshlang** [Azure/service-fabric-mesh-preview#387]
PROOF:  https://azure.microsoft.com/en-ca/resources/videos/build-2019-service-mesh-on-aks-the-future-is-now/

Ok... well https://cloudblogs.microsoft.com/industry-blog/en-gb/technetuk/2019/11/26/introduction-to-the-azure-kubernetes-service-aks-and-dev-spaces/ last paragraph hints at a talk in April 2020... so maybe not.

But opening this friendly troll-ish issue seemed more interesting than another boring one saying "When is Service Fabric Mesh" coming?  

After all this time, I'm still excited to see it launched!  ...Any updates? :D

**Comment by mattrowmsft** [comment]
We are still working on this.  I think someday there will be a talk at a conference about what we were doing all these months :-).

**Comment by MedAnd** [comment]
@mattrowmsft - I hope the talk will be about how the Atlas platform, with full support for OAM / CNAB,  powers AKS via Virtual Kubelet, powers Service Fabric Mesh, powers ACI etc etc 😄
