### ISSUE TITLE
Unable to provision resources -- requests are timing out

### ISSUE THREAD

**Issue by vyta** [Azure/service-fabric-mesh-preview#64]
```
az sbz deployment create -g newsbz --template-file sbz_rp.linux.json
```
Long running operation eventually times out.  Had one running for > 1 hour before failing with Request Timeout (Correlation ID: eee22a7a-25e3-46b7-b01e-4aa68fc22a64)

**Comment by mattrowmsft** [comment]
these images are precached now so download times should be quite a bit faster
