### ISSUE TITLE
Plans for auto-scaling

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#98]
In `docs/conceptual-docs/appmodel-overview` it was mentioned that auto-scaling is still to be added.

Can you elaborate on the plans for this please? How do you see this?

Things that come to my mind:
- **Custom metrics source(s)**: Will it have integration with Azure Monitor and Application Insights out-of-the-box?
- **Conceptually**: Will it be similar to the [Horizontal Pod Autoscaler (HPA)](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) model in Kubernetes?

**Comment by mayoatbm** [comment]
Hey folks,

We are also interested in how auto scaling will work going forward. 

Will we be able to achieve behaviors (either out of the box or by manual implementation) similar to Azure Functions autoscale i.e. based on specific sources (e.g. azure queue and service bus queue lengths, event hub message counts etc?  These autoscale + consumption based billing properties are a wonderful combination but sometimes the functions programming model isn't ideal (e.g. 10 minute limit on execution time). Service Fabric Mesh seems like it could fill this void (consumption based + autoscale + more tradition programming model). 

Thoughts? Will this be possible down the line?

**Comment by msfussell** [comment]
We have been looking into how EventGrid could integrate with Service Fabric Mesh as a way of having a resource notify its usage and this scales out the corresponding Mesh service. Nothing concrete to report at this time, but given Mesh is designed for long running services, this is a way to go.

**Comment by aloneguid** [comment]
@msfussell is there any way to control scaling from code in SFM? With full SF I can dynamically create services and scale them from another service (orchestrator service) based on my custom conditions. Is there maybe a REST api coming to do that in Mesh?

**Comment by mayoatbm** [comment]
> We have been looking into how EventGrid could integrate with Service Fabric Mesh as a way of having a resource notify its usage and this scales out the corresponding Mesh service.

So some orchestrator service in our code would listen to these event grid events at a regular interval and issue scale up/down/out commands (like @aloneguid  described)? That sounds like a good way to go (and maybe similar to what happens in the Scale Controller in Azure Functions). I guess it could depend on which services were well integrated enough into Event Grid to publish their workloads (and how often).

Thank you for responding so quickly, this is helpful for long term planning.

**Comment by tomkerkhove** [comment]
Frankly, I would only use **Azure Event Grid to emits that a scaling action has been taken** and not use it as a source to make scaling decisions on.

Scaling decisions should be made on **instance metrics** which it provides nowadays, but also based on **arbitrary metrics**. This should initially be Azure Monitor and later provide the capability to bring your own custom metrics from for example Prometheus and the like. This would allow you to define all these rules in your application manifests

Another great capability would be to be able to autoscale via **Azure Monitor Autoscale** where you can define the scaling rules outside of a Service Fabric Mesh configuration and consolidate with your other autoscaling rules.

This is a model similar to Kubernetes that works very well.

Azure Event Grid is great for eventing but I would not use it as input for this case because who will emit what events? However, having events after the fact would be great allowing you to plug in to create observability similar to what I've indicated [here](https://blog.tomkerkhove.be/2017/10/16/autoscaling-your-platform-with-azure-monitor/).

**Comment by tomkerkhove** [comment]
@mayoatbm 	That's true and that's where the integration with Azure Monitor comes in. With arbitrary I mean metrics that are not related to the running service itself but externally such as Azure Monitor, Prometheus, etc.

**The minimal scaling options for me personally are:**
- Scale on SFM service (instance) metrics
- Scale on metrics coming from Azure Monitor (and thus implicitly from Application Insights for business metrics or custom tracking of metrics) and configured via resource declaration of SFM application
- Scale automatically via Azure Monitor Autoscale initiating scaling actions (and thus implicitly from Application Insights)

Will this be covered @ChackDan 	?

**Comment by mayoatbm** [comment]
@tomkerkhove 

I just checked out the list of [metrics captured in Azure Monitor](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics) for different services and i think you're right here. There's pretty wide integration with different Azure services and many of  the metrics include clear workload indicators.

Right now, using Azure Monitor would involve something like

1. Poll Azure Monitor & Maintain State on Results
2. Based on results over a a couple of calls (e.g. moving average of queue counts in state), issue scale commands.

Anything we can do to make the above easier helps because almost every developer will want to do it.

**Comment by tomkerkhove** [comment]
@mayoatbm 	I think my point was not clear, all the scenarios that I've described are managed by Azure to triggering the scaling and involves no custom logic.

1. **Scale on SFM service (instance) metrics** -> SFM triggers the scaling for you
2. **Scale on metrics coming from Azure Monitor** _(and thus implicitly from Application Insights for business metrics or custom tracking of metrics)_ and configured via resource declaration of SFM application -> SFM runtime polls for metrics and triggers scaling action for you
3. **Scale automatically via Azure Monitor Autoscale initiating scaling actions** _(and thus implicitly from Application Insights)_ -> Azure Monitor Autoscale will consult the metrics and initiate a scaling actions towards SFM

Those are all managed by the platform, but if you want to have custom scaling that's where the custom implementation would come in.

Bonus points if you could bring your own metrics provider, ie Prometheus, and let SFM scale based off of that for scenario 2.

@ChackDan @msfussell 	 	Are scenarios 1, 2 and/or 3 being considered?

**Comment by mayoatbm** [comment]
@tomkerkhove 

That does make things clearer and I agree, Having these scenarios managed by Service Fabric Mesh would be amazing. Ease of use + consumption billing + autoscale for bursty or high volume traffic + traditional programming model etc.

It would be amazing.

**Comment by vladai78** [comment]
As per the classification @tomkerkhove put a couple of posts above:
#1 (scaling on service metrics) is already supported by SFM, but only for the built-in resource metrics (cpu and memory). We are aware of this limitation, and we are planning to remove it in the future (to get SFM auto-scaling to achieve parity with SF auto scaling).
We are considering #2 (scaling on custom/external metrics) and #3 (integration with Azure Monitor Autoscale) for future enhancements to SF and SFM auto scaling. We'll keep you in the loop with our plans.

Thanks everyone for the feedback and suggestions!

**Comment by piizei** [comment]
It should support some kind of idling, for example by scaling to 0 replicas and scaling up on network activation. Fact is that in normal business application most of the micro-services are idling most of the time.
It should support memory and CPU auto-scaling to allow design more dynamic density on the cluster.

**Comment by tomkerkhove** [comment]
Bumping - What's the status here?

**Comment by dkkapur** [comment]
@tomkerkhove following up on this and will get you an update in the next couple of days.
